/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bridge-router-ddns': RouteRecordInfo<
      '/posts/bridge-router-ddns',
      '/posts/bridge-router-ddns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CentOS-OpenStack-Queen-note': RouteRecordInfo<
      '/posts/CentOS-OpenStack-Queen-note',
      '/posts/CentOS-OpenStack-Queen-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CentOS7-docker': RouteRecordInfo<
      '/posts/CentOS7-docker',
      '/posts/CentOS7-docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CICDk8s': RouteRecordInfo<
      '/posts/CICDk8s',
      '/posts/CICDk8s',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Configuring-NoVNC-connection-to-KVM-vm': RouteRecordInfo<
      '/posts/Configuring-NoVNC-connection-to-KVM-vm',
      '/posts/Configuring-NoVNC-connection-to-KVM-vm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-images': RouteRecordInfo<
      '/posts/Docker-images',
      '/posts/Docker-images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-NextCloud': RouteRecordInfo<
      '/posts/Docker-NextCloud',
      '/posts/Docker-NextCloud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Echo-framework-route-matching&middleware': RouteRecordInfo<
      '/posts/Echo-framework-route-matching&middleware',
      '/posts/Echo-framework-route-matching&middleware',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ecs-Cos-Cloudreve': RouteRecordInfo<
      '/posts/Ecs-Cos-Cloudreve',
      '/posts/Ecs-Cos-Cloudreve',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Frpc-systemd-restart': RouteRecordInfo<
      '/posts/Frpc-systemd-restart',
      '/posts/Frpc-systemd-restart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/golang-Isekai-notebook-from-scratch': RouteRecordInfo<
      '/posts/golang-Isekai-notebook-from-scratch',
      '/posts/golang-Isekai-notebook-from-scratch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GormNote': RouteRecordInfo<
      '/posts/GormNote',
      '/posts/GormNote',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Harbor-HTTPS': RouteRecordInfo<
      '/posts/Harbor-HTTPS',
      '/posts/Harbor-HTTPS',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Hexo-to-valaxy': RouteRecordInfo<
      '/posts/Hexo-to-valaxy',
      '/posts/Hexo-to-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java-note': RouteRecordInfo<
      '/posts/Java-note',
      '/posts/Java-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/K8S1.27.0-deploy': RouteRecordInfo<
      '/posts/K8S1.27.0-deploy',
      '/posts/K8S1/27/0-deploy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/K8sJenkinsSlaveCICD': RouteRecordInfo<
      '/posts/K8sJenkinsSlaveCICD',
      '/posts/K8sJenkinsSlaveCICD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Kubernetes-note': RouteRecordInfo<
      '/posts/Kubernetes-note',
      '/posts/Kubernetes-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Kubernetes-sh': RouteRecordInfo<
      '/posts/Kubernetes-sh',
      '/posts/Kubernetes-sh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/KubernetesJenkinCICD': RouteRecordInfo<
      '/posts/KubernetesJenkinCICD',
      '/posts/KubernetesJenkinCICD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/KubeVirt-CDI': RouteRecordInfo<
      '/posts/KubeVirt-CDI',
      '/posts/KubeVirt-CDI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/KubeVirt-Getting-Start': RouteRecordInfo<
      '/posts/KubeVirt-Getting-Start',
      '/posts/KubeVirt-Getting-Start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Linux-volume': RouteRecordInfo<
      '/posts/Linux-volume',
      '/posts/Linux-volume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Manjaro-note': RouteRecordInfo<
      '/posts/Manjaro-note',
      '/posts/Manjaro-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/NeoVim-personal-note': RouteRecordInfo<
      '/posts/NeoVim-personal-note',
      '/posts/NeoVim-personal-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Online-Expansion-Ubuntu-LVM': RouteRecordInfo<
      '/posts/Online-Expansion-Ubuntu-LVM',
      '/posts/Online-Expansion-Ubuntu-LVM',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OpenCode-CodeSome-API': RouteRecordInfo<
      '/posts/OpenCode-CodeSome-API',
      '/posts/OpenCode-CodeSome-API',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OpenStack-note': RouteRecordInfo<
      '/posts/OpenStack-note',
      '/posts/OpenStack-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PHP-Nginx-website': RouteRecordInfo<
      '/posts/PHP-Nginx-website',
      '/posts/PHP-Nginx-website',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PowerShell-dev-config-note': RouteRecordInfo<
      '/posts/PowerShell-dev-config-note',
      '/posts/PowerShell-dev-config-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/shell-practice': RouteRecordInfo<
      '/posts/shell-practice',
      '/posts/shell-practice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/SRS-liveStream': RouteRecordInfo<
      '/posts/SRS-liveStream',
      '/posts/SRS-liveStream',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Troubleshooting-and-Practice-of-Docker-Container-Networking-and-Firewalld-Zone-Conflicts': RouteRecordInfo<
      '/posts/Troubleshooting-and-Practice-of-Docker-Container-Networking-and-Firewalld-Zone-Conflicts',
      '/posts/Troubleshooting-and-Practice-of-Docker-Container-Networking-and-Firewalld-Zone-Conflicts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ubuntu-Docker-Compose': RouteRecordInfo<
      '/posts/Ubuntu-Docker-Compose',
      '/posts/Ubuntu-Docker-Compose',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ubuntu-Nginx-useage': RouteRecordInfo<
      '/posts/Ubuntu-Nginx-useage',
      '/posts/Ubuntu-Nginx-useage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ubuntu-OpenStack-Yoga-Zed': RouteRecordInfo<
      '/posts/Ubuntu-OpenStack-Yoga-Zed',
      '/posts/Ubuntu-OpenStack-Yoga-Zed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ubuntu22.04-k8s-deploy': RouteRecordInfo<
      '/posts/ubuntu22.04-k8s-deploy',
      '/posts/ubuntu22/04-k8s-deploy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/XiaoMi-Book-12-4': RouteRecordInfo<
      '/posts/XiaoMi-Book-12-4',
      '/posts/XiaoMi-Book-12-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-beta.2_magicast@0.5.3_vue@3.5.34_typescript@7.0.2_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-beta.2_@babel+parser@7.29.7_@nuxt+kit@3.21.10_magicast@0.5.3__@types+markd_eeef79e43f98981bd64317fb6ef1a1ab/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-beta.2_magicast@0.5.3_vue@3.5.34_typescript@7.0.2_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-beta.2_magicast@0.5.3_vue@3.5.34_typescript@7.0.2_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/bridge-router-ddns.md': {
      routes:
        | '/posts/bridge-router-ddns'
      views:
        | never
    }
    'pages/posts/CentOS-OpenStack-Queen-note.md': {
      routes:
        | '/posts/CentOS-OpenStack-Queen-note'
      views:
        | never
    }
    'pages/posts/CentOS7-docker.md': {
      routes:
        | '/posts/CentOS7-docker'
      views:
        | never
    }
    'pages/posts/CICDk8s.md': {
      routes:
        | '/posts/CICDk8s'
      views:
        | never
    }
    'pages/posts/Configuring-NoVNC-connection-to-KVM-vm.md': {
      routes:
        | '/posts/Configuring-NoVNC-connection-to-KVM-vm'
      views:
        | never
    }
    'pages/posts/Docker-images.md': {
      routes:
        | '/posts/Docker-images'
      views:
        | never
    }
    'pages/posts/Docker-NextCloud.md': {
      routes:
        | '/posts/Docker-NextCloud'
      views:
        | never
    }
    'pages/posts/Echo-framework-route-matching&middleware.md': {
      routes:
        | '/posts/Echo-framework-route-matching&middleware'
      views:
        | never
    }
    'pages/posts/Ecs-Cos-Cloudreve.md': {
      routes:
        | '/posts/Ecs-Cos-Cloudreve'
      views:
        | never
    }
    'pages/posts/Frpc-systemd-restart.md': {
      routes:
        | '/posts/Frpc-systemd-restart'
      views:
        | never
    }
    'pages/posts/golang-Isekai-notebook-from-scratch.md': {
      routes:
        | '/posts/golang-Isekai-notebook-from-scratch'
      views:
        | never
    }
    'pages/posts/GormNote.md': {
      routes:
        | '/posts/GormNote'
      views:
        | never
    }
    'pages/posts/Harbor-HTTPS.md': {
      routes:
        | '/posts/Harbor-HTTPS'
      views:
        | never
    }
    'pages/posts/Hexo-to-valaxy.md': {
      routes:
        | '/posts/Hexo-to-valaxy'
      views:
        | never
    }
    'pages/posts/Java-note.md': {
      routes:
        | '/posts/Java-note'
      views:
        | never
    }
    'pages/posts/K8S1.27.0-deploy.md': {
      routes:
        | '/posts/K8S1.27.0-deploy'
      views:
        | never
    }
    'pages/posts/K8sJenkinsSlaveCICD.md': {
      routes:
        | '/posts/K8sJenkinsSlaveCICD'
      views:
        | never
    }
    'pages/posts/Kubernetes-note.md': {
      routes:
        | '/posts/Kubernetes-note'
      views:
        | never
    }
    'pages/posts/Kubernetes-sh.md': {
      routes:
        | '/posts/Kubernetes-sh'
      views:
        | never
    }
    'pages/posts/KubernetesJenkinCICD.md': {
      routes:
        | '/posts/KubernetesJenkinCICD'
      views:
        | never
    }
    'pages/posts/KubeVirt-CDI.md': {
      routes:
        | '/posts/KubeVirt-CDI'
      views:
        | never
    }
    'pages/posts/KubeVirt-Getting-Start.md': {
      routes:
        | '/posts/KubeVirt-Getting-Start'
      views:
        | never
    }
    'pages/posts/Linux-volume.md': {
      routes:
        | '/posts/Linux-volume'
      views:
        | never
    }
    'pages/posts/Manjaro-note.md': {
      routes:
        | '/posts/Manjaro-note'
      views:
        | never
    }
    'pages/posts/NeoVim-personal-note.md': {
      routes:
        | '/posts/NeoVim-personal-note'
      views:
        | never
    }
    'pages/posts/Online-Expansion-Ubuntu-LVM.md': {
      routes:
        | '/posts/Online-Expansion-Ubuntu-LVM'
      views:
        | never
    }
    'pages/posts/OpenCode-CodeSome-API.md': {
      routes:
        | '/posts/OpenCode-CodeSome-API'
      views:
        | never
    }
    'pages/posts/OpenStack-note.md': {
      routes:
        | '/posts/OpenStack-note'
      views:
        | never
    }
    'pages/posts/PHP-Nginx-website.md': {
      routes:
        | '/posts/PHP-Nginx-website'
      views:
        | never
    }
    'pages/posts/PowerShell-dev-config-note.md': {
      routes:
        | '/posts/PowerShell-dev-config-note'
      views:
        | never
    }
    'pages/posts/shell-practice.md': {
      routes:
        | '/posts/shell-practice'
      views:
        | never
    }
    'pages/posts/SRS-liveStream.md': {
      routes:
        | '/posts/SRS-liveStream'
      views:
        | never
    }
    'pages/posts/Troubleshooting-and-Practice-of-Docker-Container-Networking-and-Firewalld-Zone-Conflicts.md': {
      routes:
        | '/posts/Troubleshooting-and-Practice-of-Docker-Container-Networking-and-Firewalld-Zone-Conflicts'
      views:
        | never
    }
    'pages/posts/Ubuntu-Docker-Compose.md': {
      routes:
        | '/posts/Ubuntu-Docker-Compose'
      views:
        | never
    }
    'pages/posts/Ubuntu-Nginx-useage.md': {
      routes:
        | '/posts/Ubuntu-Nginx-useage'
      views:
        | never
    }
    'pages/posts/Ubuntu-OpenStack-Yoga-Zed.md': {
      routes:
        | '/posts/Ubuntu-OpenStack-Yoga-Zed'
      views:
        | never
    }
    'pages/posts/ubuntu22.04-k8s-deploy.md': {
      routes:
        | '/posts/ubuntu22.04-k8s-deploy'
      views:
        | never
    }
    'pages/posts/XiaoMi-Book-12-4.md': {
      routes:
        | '/posts/XiaoMi-Book-12-4'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
