/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/从零开始的Go语言异世界笔记': RouteRecordInfo<
      '/posts/从零开始的Go语言异世界笔记',
      '/posts/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E7%9A%84Go%E8%AF%AD%E8%A8%80%E5%BC%82%E4%B8%96%E7%95%8C%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于Echo框架路由匹配与中间件的坑': RouteRecordInfo<
      '/posts/关于Echo框架路由匹配与中间件的坑',
      '/posts/%E5%85%B3%E4%BA%8EEcho%E6%A1%86%E6%9E%B6%E8%B7%AF%E7%94%B1%E5%8C%B9%E9%85%8D%E4%B8%8E%E4%B8%AD%E9%97%B4%E4%BB%B6%E7%9A%84%E5%9D%91',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/解决Docker容器互联与Firewalld区域冲突的排查与实践': RouteRecordInfo<
      '/posts/解决Docker容器互联与Firewalld区域冲突的排查与实践',
      '/posts/%E8%A7%A3%E5%86%B3Docker%E5%AE%B9%E5%99%A8%E4%BA%92%E8%81%94%E4%B8%8EFirewalld%E5%8C%BA%E5%9F%9F%E5%86%B2%E7%AA%81%E7%9A%84%E6%8E%92%E6%9F%A5%E4%B8%8E%E5%AE%9E%E8%B7%B5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/配置NoVNC连接Kvm虚拟机': RouteRecordInfo<
      '/posts/配置NoVNC连接Kvm虚拟机',
      '/posts/%E9%85%8D%E7%BD%AENoVNC%E8%BF%9E%E6%8E%A5Kvm%E8%99%9A%E6%8B%9F%E6%9C%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bridge-router-ddns': RouteRecordInfo<
      '/posts/bridge-router-ddns',
      '/posts/bridge-router-ddns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CentOS-OpenStack-Queen手记': RouteRecordInfo<
      '/posts/CentOS-OpenStack-Queen手记',
      '/posts/CentOS-OpenStack-Queen%E6%89%8B%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CentOS7-docker': RouteRecordInfo<
      '/posts/CentOS7-docker',
      '/posts/CentOS7-docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CICDk8s': RouteRecordInfo<
      '/posts/CICDk8s',
      '/posts/CICDk8s',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-images': RouteRecordInfo<
      '/posts/Docker-images',
      '/posts/Docker-images',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker-NextCloud': RouteRecordInfo<
      '/posts/Docker-NextCloud',
      '/posts/Docker-NextCloud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ecs-Cos-Cloudreve': RouteRecordInfo<
      '/posts/Ecs-Cos-Cloudreve',
      '/posts/Ecs-Cos-Cloudreve',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Frpc-systemd-restart': RouteRecordInfo<
      '/posts/Frpc-systemd-restart',
      '/posts/Frpc-systemd-restart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GormNote': RouteRecordInfo<
      '/posts/GormNote',
      '/posts/GormNote',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Harbor配置HTTPS': RouteRecordInfo<
      '/posts/Harbor配置HTTPS',
      '/posts/Harbor%E9%85%8D%E7%BD%AEHTTPS',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Hexo-to-valaxy': RouteRecordInfo<
      '/posts/Hexo-to-valaxy',
      '/posts/Hexo-to-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java-note': RouteRecordInfo<
      '/posts/Java-note',
      '/posts/Java-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/K8S1.27.0-deploy': RouteRecordInfo<
      '/posts/K8S1.27.0-deploy',
      '/posts/K8S1/27/0-deploy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/K8sJenkinsSlaveCICD': RouteRecordInfo<
      '/posts/K8sJenkinsSlaveCICD',
      '/posts/K8sJenkinsSlaveCICD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Kubernetes-note': RouteRecordInfo<
      '/posts/Kubernetes-note',
      '/posts/Kubernetes-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Kubernetes-sh': RouteRecordInfo<
      '/posts/Kubernetes-sh',
      '/posts/Kubernetes-sh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/KubernetesJenkinCICD': RouteRecordInfo<
      '/posts/KubernetesJenkinCICD',
      '/posts/KubernetesJenkinCICD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/KubeVirt-CDI': RouteRecordInfo<
      '/posts/KubeVirt-CDI',
      '/posts/KubeVirt-CDI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/KubeVirt-Getting-Start': RouteRecordInfo<
      '/posts/KubeVirt-Getting-Start',
      '/posts/KubeVirt-Getting-Start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Linux-volume': RouteRecordInfo<
      '/posts/Linux-volume',
      '/posts/Linux-volume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Manjaro-note': RouteRecordInfo<
      '/posts/Manjaro-note',
      '/posts/Manjaro-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/NeoVim个人配置笔记': RouteRecordInfo<
      '/posts/NeoVim个人配置笔记',
      '/posts/NeoVim%E4%B8%AA%E4%BA%BA%E9%85%8D%E7%BD%AE%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Online-Expansion-Ubuntu-LVM': RouteRecordInfo<
      '/posts/Online-Expansion-Ubuntu-LVM',
      '/posts/Online-Expansion-Ubuntu-LVM',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OpenCode对接CodeSomeAPI': RouteRecordInfo<
      '/posts/OpenCode对接CodeSomeAPI',
      '/posts/OpenCode%E5%AF%B9%E6%8E%A5CodeSomeAPI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OpenStack-note': RouteRecordInfo<
      '/posts/OpenStack-note',
      '/posts/OpenStack-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PHP-Nginx-website': RouteRecordInfo<
      '/posts/PHP-Nginx-website',
      '/posts/PHP-Nginx-website',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PowerShell开发配置指北': RouteRecordInfo<
      '/posts/PowerShell开发配置指北',
      '/posts/PowerShell%E5%BC%80%E5%8F%91%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8C%97',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/shell-practice': RouteRecordInfo<
      '/posts/shell-practice',
      '/posts/shell-practice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/SRS-liveStream': RouteRecordInfo<
      '/posts/SRS-liveStream',
      '/posts/SRS-liveStream',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ubuntu-Docker-Compose': RouteRecordInfo<
      '/posts/Ubuntu-Docker-Compose',
      '/posts/Ubuntu-Docker-Compose',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ubuntu-Nginx-useage': RouteRecordInfo<
      '/posts/Ubuntu-Nginx-useage',
      '/posts/Ubuntu-Nginx-useage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Ubuntu-OpenStack-Yoga-Zed': RouteRecordInfo<
      '/posts/Ubuntu-OpenStack-Yoga-Zed',
      '/posts/Ubuntu-OpenStack-Yoga-Zed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ubuntu22.04-k8s-deploy': RouteRecordInfo<
      '/posts/ubuntu22.04-k8s-deploy',
      '/posts/ubuntu22/04-k8s-deploy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/XiaoMi-Book-12-4': RouteRecordInfo<
      '/posts/XiaoMi-Book-12-4',
      '/posts/XiaoMi-Book-12-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.12_rollup@4.44.2_vue@3.5.4_typescript@5.6.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.12_@babel+parser@7.28.5_@nuxt+kit@3.13.2_rollup@4.44.2__@types+markdown-it@_2dd23530c962496beb6205551479be72/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.12_rollup@4.44.2_vue@3.5.4_typescript@5.6.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.12_rollup@4.44.2_vue@3.5.4_typescript@5.6.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/从零开始的Go语言异世界笔记.md': {
      routes:
        | '/posts/从零开始的Go语言异世界笔记'
      views:
        | never
    }
    'pages/posts/关于Echo框架路由匹配与中间件的坑.md': {
      routes:
        | '/posts/关于Echo框架路由匹配与中间件的坑'
      views:
        | never
    }
    'pages/posts/解决Docker容器互联与Firewalld区域冲突的排查与实践.md': {
      routes:
        | '/posts/解决Docker容器互联与Firewalld区域冲突的排查与实践'
      views:
        | never
    }
    'pages/posts/配置NoVNC连接Kvm虚拟机.md': {
      routes:
        | '/posts/配置NoVNC连接Kvm虚拟机'
      views:
        | never
    }
    'pages/posts/bridge-router-ddns.md': {
      routes:
        | '/posts/bridge-router-ddns'
      views:
        | never
    }
    'pages/posts/CentOS-OpenStack-Queen手记.md': {
      routes:
        | '/posts/CentOS-OpenStack-Queen手记'
      views:
        | never
    }
    'pages/posts/CentOS7-docker.md': {
      routes:
        | '/posts/CentOS7-docker'
      views:
        | never
    }
    'pages/posts/CICDk8s.md': {
      routes:
        | '/posts/CICDk8s'
      views:
        | never
    }
    'pages/posts/Docker-images.md': {
      routes:
        | '/posts/Docker-images'
      views:
        | never
    }
    'pages/posts/Docker-NextCloud.md': {
      routes:
        | '/posts/Docker-NextCloud'
      views:
        | never
    }
    'pages/posts/Ecs-Cos-Cloudreve.md': {
      routes:
        | '/posts/Ecs-Cos-Cloudreve'
      views:
        | never
    }
    'pages/posts/Frpc-systemd-restart.md': {
      routes:
        | '/posts/Frpc-systemd-restart'
      views:
        | never
    }
    'pages/posts/GormNote.md': {
      routes:
        | '/posts/GormNote'
      views:
        | never
    }
    'pages/posts/Harbor配置HTTPS.md': {
      routes:
        | '/posts/Harbor配置HTTPS'
      views:
        | never
    }
    'pages/posts/Hexo-to-valaxy.md': {
      routes:
        | '/posts/Hexo-to-valaxy'
      views:
        | never
    }
    'pages/posts/Java-note.md': {
      routes:
        | '/posts/Java-note'
      views:
        | never
    }
    'pages/posts/K8S1.27.0-deploy.md': {
      routes:
        | '/posts/K8S1.27.0-deploy'
      views:
        | never
    }
    'pages/posts/K8sJenkinsSlaveCICD.md': {
      routes:
        | '/posts/K8sJenkinsSlaveCICD'
      views:
        | never
    }
    'pages/posts/Kubernetes-note.md': {
      routes:
        | '/posts/Kubernetes-note'
      views:
        | never
    }
    'pages/posts/Kubernetes-sh.md': {
      routes:
        | '/posts/Kubernetes-sh'
      views:
        | never
    }
    'pages/posts/KubernetesJenkinCICD.md': {
      routes:
        | '/posts/KubernetesJenkinCICD'
      views:
        | never
    }
    'pages/posts/KubeVirt-CDI.md': {
      routes:
        | '/posts/KubeVirt-CDI'
      views:
        | never
    }
    'pages/posts/KubeVirt-Getting-Start.md': {
      routes:
        | '/posts/KubeVirt-Getting-Start'
      views:
        | never
    }
    'pages/posts/Linux-volume.md': {
      routes:
        | '/posts/Linux-volume'
      views:
        | never
    }
    'pages/posts/Manjaro-note.md': {
      routes:
        | '/posts/Manjaro-note'
      views:
        | never
    }
    'pages/posts/NeoVim个人配置笔记.md': {
      routes:
        | '/posts/NeoVim个人配置笔记'
      views:
        | never
    }
    'pages/posts/Online-Expansion-Ubuntu-LVM.md': {
      routes:
        | '/posts/Online-Expansion-Ubuntu-LVM'
      views:
        | never
    }
    'pages/posts/OpenCode对接CodeSomeAPI.md': {
      routes:
        | '/posts/OpenCode对接CodeSomeAPI'
      views:
        | never
    }
    'pages/posts/OpenStack-note.md': {
      routes:
        | '/posts/OpenStack-note'
      views:
        | never
    }
    'pages/posts/PHP-Nginx-website.md': {
      routes:
        | '/posts/PHP-Nginx-website'
      views:
        | never
    }
    'pages/posts/PowerShell开发配置指北.md': {
      routes:
        | '/posts/PowerShell开发配置指北'
      views:
        | never
    }
    'pages/posts/shell-practice.md': {
      routes:
        | '/posts/shell-practice'
      views:
        | never
    }
    'pages/posts/SRS-liveStream.md': {
      routes:
        | '/posts/SRS-liveStream'
      views:
        | never
    }
    'pages/posts/Ubuntu-Docker-Compose.md': {
      routes:
        | '/posts/Ubuntu-Docker-Compose'
      views:
        | never
    }
    'pages/posts/Ubuntu-Nginx-useage.md': {
      routes:
        | '/posts/Ubuntu-Nginx-useage'
      views:
        | never
    }
    'pages/posts/Ubuntu-OpenStack-Yoga-Zed.md': {
      routes:
        | '/posts/Ubuntu-OpenStack-Yoga-Zed'
      views:
        | never
    }
    'pages/posts/ubuntu22.04-k8s-deploy.md': {
      routes:
        | '/posts/ubuntu22.04-k8s-deploy'
      views:
        | never
    }
    'pages/posts/XiaoMi-Book-12-4.md': {
      routes:
        | '/posts/XiaoMi-Book-12-4'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
