/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/bridge-router-ddns': RouteRecordInfo<'/posts/bridge-router-ddns', '/posts/bridge-router-ddns', Record<never, never>, Record<never, never>>,
    '/posts/CentOS-OpenStack-Queen手记': RouteRecordInfo<'/posts/CentOS-OpenStack-Queen手记', '/posts/CentOS-OpenStack-Queen手记', Record<never, never>, Record<never, never>>,
    '/posts/CentOS7-docker': RouteRecordInfo<'/posts/CentOS7-docker', '/posts/CentOS7-docker', Record<never, never>, Record<never, never>>,
    '/posts/CICDk8s': RouteRecordInfo<'/posts/CICDk8s', '/posts/CICDk8s', Record<never, never>, Record<never, never>>,
    '/posts/Docker-images': RouteRecordInfo<'/posts/Docker-images', '/posts/Docker-images', Record<never, never>, Record<never, never>>,
    '/posts/Docker-NextCloud': RouteRecordInfo<'/posts/Docker-NextCloud', '/posts/Docker-NextCloud', Record<never, never>, Record<never, never>>,
    '/posts/Ecs-Cos-Cloudreve': RouteRecordInfo<'/posts/Ecs-Cos-Cloudreve', '/posts/Ecs-Cos-Cloudreve', Record<never, never>, Record<never, never>>,
    '/posts/Frpc-systemd-restart': RouteRecordInfo<'/posts/Frpc-systemd-restart', '/posts/Frpc-systemd-restart', Record<never, never>, Record<never, never>>,
    '/posts/Golang-Prime': RouteRecordInfo<'/posts/Golang-Prime', '/posts/Golang-Prime', Record<never, never>, Record<never, never>>,
    '/posts/GormNote': RouteRecordInfo<'/posts/GormNote', '/posts/GormNote', Record<never, never>, Record<never, never>>,
    '/posts/Hexo-to-valaxy': RouteRecordInfo<'/posts/Hexo-to-valaxy', '/posts/Hexo-to-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Java-note': RouteRecordInfo<'/posts/Java-note', '/posts/Java-note', Record<never, never>, Record<never, never>>,
    '/posts/K8S1.27.0-deploy': RouteRecordInfo<'/posts/K8S1.27.0-deploy', '/posts/K8S1/27/0-deploy', Record<never, never>, Record<never, never>>,
    '/posts/K8sJenkinsSlaveCICD': RouteRecordInfo<'/posts/K8sJenkinsSlaveCICD', '/posts/K8sJenkinsSlaveCICD', Record<never, never>, Record<never, never>>,
    '/posts/Kubernetes-note': RouteRecordInfo<'/posts/Kubernetes-note', '/posts/Kubernetes-note', Record<never, never>, Record<never, never>>,
    '/posts/Kubernetes-sh': RouteRecordInfo<'/posts/Kubernetes-sh', '/posts/Kubernetes-sh', Record<never, never>, Record<never, never>>,
    '/posts/KubernetesJenkinCICD': RouteRecordInfo<'/posts/KubernetesJenkinCICD', '/posts/KubernetesJenkinCICD', Record<never, never>, Record<never, never>>,
    '/posts/KubeVirt-CDI': RouteRecordInfo<'/posts/KubeVirt-CDI', '/posts/KubeVirt-CDI', Record<never, never>, Record<never, never>>,
    '/posts/KubeVirt-Getting-Start': RouteRecordInfo<'/posts/KubeVirt-Getting-Start', '/posts/KubeVirt-Getting-Start', Record<never, never>, Record<never, never>>,
    '/posts/Linux-volume': RouteRecordInfo<'/posts/Linux-volume', '/posts/Linux-volume', Record<never, never>, Record<never, never>>,
    '/posts/Manjaro-note': RouteRecordInfo<'/posts/Manjaro-note', '/posts/Manjaro-note', Record<never, never>, Record<never, never>>,
    '/posts/NeoVim个人配置笔记': RouteRecordInfo<'/posts/NeoVim个人配置笔记', '/posts/NeoVim个人配置笔记', Record<never, never>, Record<never, never>>,
    '/posts/Online-Expansion-Ubuntu-LVM': RouteRecordInfo<'/posts/Online-Expansion-Ubuntu-LVM', '/posts/Online-Expansion-Ubuntu-LVM', Record<never, never>, Record<never, never>>,
    '/posts/OpenStack-note': RouteRecordInfo<'/posts/OpenStack-note', '/posts/OpenStack-note', Record<never, never>, Record<never, never>>,
    '/posts/PHP-Nginx-website': RouteRecordInfo<'/posts/PHP-Nginx-website', '/posts/PHP-Nginx-website', Record<never, never>, Record<never, never>>,
    '/posts/PowerShell开发配置指北': RouteRecordInfo<'/posts/PowerShell开发配置指北', '/posts/PowerShell开发配置指北', Record<never, never>, Record<never, never>>,
    '/posts/shell-practice': RouteRecordInfo<'/posts/shell-practice', '/posts/shell-practice', Record<never, never>, Record<never, never>>,
    '/posts/SRS-liveStream': RouteRecordInfo<'/posts/SRS-liveStream', '/posts/SRS-liveStream', Record<never, never>, Record<never, never>>,
    '/posts/Ubuntu-Docker-Compose': RouteRecordInfo<'/posts/Ubuntu-Docker-Compose', '/posts/Ubuntu-Docker-Compose', Record<never, never>, Record<never, never>>,
    '/posts/Ubuntu-Nginx-useage': RouteRecordInfo<'/posts/Ubuntu-Nginx-useage', '/posts/Ubuntu-Nginx-useage', Record<never, never>, Record<never, never>>,
    '/posts/Ubuntu-OpenStack-Yoga-Zed': RouteRecordInfo<'/posts/Ubuntu-OpenStack-Yoga-Zed', '/posts/Ubuntu-OpenStack-Yoga-Zed', Record<never, never>, Record<never, never>>,
    '/posts/ubuntu22.04-k8s-deploy': RouteRecordInfo<'/posts/ubuntu22.04-k8s-deploy', '/posts/ubuntu22/04-k8s-deploy', Record<never, never>, Record<never, never>>,
    '/posts/XiaoMi-Book-12-4': RouteRecordInfo<'/posts/XiaoMi-Book-12-4', '/posts/XiaoMi-Book-12-4', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
